//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Auten_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Connection_Equipment
    {
        public int ID_con { get; set; }
        public int ID_eq { get; set; }
        public string Conn_adress { get; set; }
        public string Install_loc { get; set; }
        public string Connection { get; set; }
    
        public virtual Equpment Equpment { get; set; }
    }
}
