//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Auten_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equpment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Equpment()
        {
            this.Connection_Equipment = new HashSet<Connection_Equipment>();
        }
    
        public int ID_eq { get; set; }
        public string Title { get; set; }
        public int ID_type { get; set; }
        public int Number { get; set; }
        public int MAC { get; set; }
        public int IP { get; set; }
        public int Phone { get; set; }
        public System.DateTime Data { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Connection_Equipment> Connection_Equipment { get; set; }
        public virtual Type_Equipment Type_Equipment { get; set; }
    }
}
